from fpdf import FPDF
import tempfile
import datetime
import os

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'FloraCare AI Diagnosis Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by FloraCare AI - Consult an expert before using chemicals.', 0, 0, 'C')

    @staticmethod
    def _clean_text(text: str) -> str:
        """
        Sanitizes text for FPDF (Latin-1).
        Replaces common unicode characters affecting PDFs.
        """
        if not text:
            return ""
        
        replacements = {
            '\u2013': '-',   # en-dash
            '\u2014': '--',  # em-dash
            '\u2018': "'",   # left single quote
            '\u2019': "'",   # right single quote
            '\u201c': '"',   # left double quote
            '\u201d': '"',   # right double quote
            '\u2026': '...', # ellipsis
            '\u00a0': ' ',   # non-breaking space
        }
        
        for char, replacement in replacements.items():
            text = text.replace(char, replacement)
            
        # Final safety net: encode to latin-1, replacing errors with '?'
        return text.encode('latin-1', 'replace').decode('latin-1')

def generate_pdf_report(image_path: str, diagnosis_data: dict) -> str:
    """
    Generates a PDF report.
    image_path: Path to the plant image.
    diagnosis_data: Dict containing:
        - date (optional)
        - disease_name
        - confidence_score (e.g. "98.5%")
        - trust_label (e.g. "HIGH")
        - analysis (text)
        - treatment_plan (list of strings)
    """
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # 1. Add Date
    pdf.set_font("Arial", size=10)
    date_str = diagnosis_data.get('date', datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    pdf.cell(0, 10, f"Date: {date_str}", ln=True, align='R')
    pdf.ln(5)

    # 2. Add Image (Centered and Scaled)
    # Scale image to width 100mm, keep aspect ratio
    try:
        # Check margins to calculate center
        # Default margins are 10mm (1cm) in FPDF if not set
        # But we want to be explicit or use pdf.w
        image_width = 100  # 100mm wide
        x_centered = (pdf.w - image_width) / 2
        
        pdf.image(image_path, x=x_centered, w=image_width)
        pdf.ln(10) # Add space after image
    except Exception as e:
        pdf.set_text_color(255, 0, 0)
        pdf.cell(0, 10, f"Error loading image: {str(e)}", ln=True)
        pdf.set_text_color(0, 0, 0)

    # 3. Disease & Confidence Section
    pdf.set_font("Arial", 'B', 14)
    pdf.set_fill_color(230, 230, 230) # Light gray background
    
    disease = PDFReport._clean_text(diagnosis_data.get('disease_name', 'Unknown'))
    confidence = PDFReport._clean_text(diagnosis_data.get('confidence_score', '0%'))
    trust = PDFReport._clean_text(diagnosis_data.get('trust_label', 'N/A'))
    
    # Use MultiCell to prevent cut-off if disease name is long
    # We pass 0 width for full width
    pdf.multi_cell(0, 10, f"Disease Detected: {disease}", fill=True, align='L')
    
    pdf.set_font("Arial", 'B', 12)
    # Reset fill? cell uses fill if set.
    # The user example didn't reset fill but used cell() without fill param, defaulting to false usually?
    # FPDF cell: fill is boolean. Default False.
    pdf.cell(0, 10, f"Confidence: {confidence} ({trust})", ln=True)
    pdf.ln(5)

    # Helper for Smart Page Breaks
    def check_space(height_needed):
        # A4 height ~297mm. Bottom margin 15mm. Trigger break around 270mm.
        if pdf.get_y() + height_needed > 270:
            pdf.add_page()

    # 4a. Weather Context (Optional)
    weather = diagnosis_data.get('weather_context')
    if weather and isinstance(weather, str):
        check_space(25) # Header + ~2 lines
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "Weather Context:", ln=True)
        pdf.set_font("Arial", size=11)
        pdf.multi_cell(0, 7, PDFReport._clean_text(weather))
        pdf.ln(5)

    # 4b. Identified Symptoms
    symptoms = diagnosis_data.get('visual_symptoms', [])
    if symptoms and isinstance(symptoms, list):
        check_space(30) # Header + ~2-3 lines
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "Identified Symptoms:", ln=True)
        pdf.set_font("Arial", size=11)
        for sym in symptoms:
            clean_sym = PDFReport._clean_text(sym)
            pdf.multi_cell(0, 7, f"- {clean_sym}")
        pdf.ln(5)

    # 4. Biological Analysis (The Fix for Cut-off Text)
    check_space(40) # Header + decent chunk of text
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Biological Analysis:", ln=True)
    pdf.set_font("Arial", size=11)
    
    analysis_text = PDFReport._clean_text(diagnosis_data.get('analysis', 'No analysis provided.'))
    # multi_cell(width, height, text) - width=0 means "full width"
    pdf.multi_cell(0, 7, analysis_text)
    pdf.ln(5)

    # 5. Treatment Plan
    check_space(40) # Header + decent chunk of text
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Treatment Plan:", ln=True)
    pdf.set_font("Arial", size=11)
    
    treatments = diagnosis_data.get('treatment_plan', [])
    if isinstance(treatments, list):
        for step in treatments:
            clean_step = PDFReport._clean_text(step)
            # Add a bullet point using specific character code or simple dash
            pdf.multi_cell(0, 7, f"- {clean_step}")
    else:
        pdf.multi_cell(0, 7, PDFReport._clean_text(str(treatments)))

    # Save to temp file
    temp_pdf = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    temp_pdf.close() # Close so FPDF can write to it
        
    pdf.output(temp_pdf.name)
    return temp_pdf.name
